version: '3.8'

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/mafia
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    restart: unless-stopped


volumes:
  mongodb_data: